[WIP] Brigadier Command Api v3
Legacy-Fabric/fabric pull request #102
Opened 2021-11-30 03:13 UTC by hYdos

Can't use V2 just in case someone actually used v2 in their mod in the short time it was up.

2021-11-30 03:40 UTC, PseudoDistant commented
I rescind my f den.

2021-11-30 07:07 UTC, BoogieMonster1O1 requested changes
rename the module to mention brigadier
rename the packages

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on build.gradle
> +		implementation("com.mojang:brigadier:1.0.17")
this doesn't include brigadier

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/base/src/main/java/net/legacyfabric/fabric/impl/base/mixin/RealmsBridgeMixin.java
> +public class RealmsBridgeMixin {
👎

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/commands/src/main/java/net/legacyfabric/fabric/commands/BrigadierCommand.java
> +	public void execute(CommandSource source, String[] args) {
why's this empty

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/commands/src/main/java/net/legacyfabric/fabric/commands/BrigadierCommand.java
> +		return false;
fix this

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/commands/src/main/java/net/legacyfabric/fabric/commands/BrigadierCommand.java
> +		return 0;
this as well

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/commands/src/main/java/net/legacyfabric/fabric/commands/BrigadierCommand.java
> +public class BrigadierCommand implements Command {
don't implement `Command`
extend `AbstractCommand`

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/commands/src/main/java/net/legacyfabric/fabric/commands/CommandRegisterCallback.java
> +		void onCommandRegistration(CommandDispatcher<CommandSource> dispatcher, MinecraftClient client, Profiler profiler);
unsafe usage of `MinecraftClient` on the server thread

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/commands/src/main/java/net/legacyfabric/fabric/commands/CommandRegisterCallback.java
> +	public static final Event<ClientCommandRegister> CLIENT = EventFactory.createArrayBacked(ClientCommandRegister.class, callbacks -> (dispatcher, client, profiler) -> {
`CLIENT` is misleading
should be renamed to integrated

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/commands/src/main/java/net/legacyfabric/fabric/commands/CommandRegisterCallback.java
> +	public static final Event<ServerCommandRegister> SERVER = EventFactory.createArrayBacked(ServerCommandRegister.class, callbacks -> (dispatcher, server, profiler) -> {
ditto
dedicated

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/commands/src/main/java/net/legacyfabric/fabric/commands/mixin/CommandManagerMixin.java
> +	@Inject(method = "<init>", at = @At("TAIL"))
you don't need a mixin for this

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/commands/src/main/java/net/legacyfabric/fabric/commands/mixin/CommandManagerMixin.java
> +	public List<Command> method_5983(CommandSource source) {
👎 
there are better ways to do this
I did it with sponge cmd api without a massive hack

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on modules/commands/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
wrong homepage

2021-11-30 07:07 UTC, BoogieMonster1O1 commented on settings.gradle
> +addModule("commands", "legacy-fabric-commands-v3")
brigadier-commands

2021-11-30 07:57 UTC, ramidzkh commented
So what happened to this https://github.com/Legacy-Fabric/fabric/pull/99#issuecomment-980840833

2021-11-30 08:01 UTC, hYdos commented
I made an compromise. This was the best option as it allows for portability and ease of use.

2021-12-03 09:30 UTC, ramidzkh commented
So when are you pushing the changes you resolved the reviews for

2022-04-18 20:48 UTC, arthurbambou commented
stale

2022-04-18 20:48 UTC, closed without merging