World generation events
Legacy-Fabric/fabric pull request #52
Opened 2020-11-07 11:05 UTC by BoogieMonster1O1

Adds worldgen related events

- [x] Grass color event
- [x] Water color event
- [x] Foliage color event
- [x] Ore registration event
- [ ] Ore generation cancelling event
- [ ] Feature generation cancelling event
- [ ] Biome decoration event

2020-12-27 03:16 UTC, BoogieMonster1O1 commented
gonna yeet this and redo it next year

2021-03-03 02:08 UTC, BoogieMonster1O1 commented
yes it bacc

2021-03-03 04:20 UTC, BluCobalt requested changes
make build not fail

2021-03-03 04:27 UTC, BluCobalt requested changes
ubrh

2021-03-03 04:27 UTC, BluCobalt commented on fabric-api-base/src/main/java/net/fabricmc/fabric/api/util/IntActionResult.java
> + * Copyright (c) 2016, 2017, 2018, 2019 FabricMC
shouldn't the copyright say legacy fabric?

2021-03-03 04:27 UTC, BluCobalt commented on fabric-world-generation-events-v1/src/main/java/net/fabricmc/fabric/api/worldgen/event/v1/BiomeDecorationEvents.java
> + * Copyright (c) 2016, 2017, 2018, 2019 FabricMC
legacy fabric?

2021-03-03 04:27 UTC, BluCobalt commented on fabric-world-generation-events-v1/src/main/java/net/fabricmc/fabric/api/worldgen/event/v1/OreEntry.java
> + * Copyright (c) 2016, 2017, 2018, 2019 FabricMC
lf?

2021-03-03 04:27 UTC, BluCobalt commented on fabric-world-generation-events-v1/src/main/java/net/fabricmc/fabric/api/worldgen/event/v1/OreRegistry.java
> + * Copyright (c) 2016, 2017, 2018, 2019 FabricMC
bruh

2021-03-03 04:27 UTC, BluCobalt commented on fabric-world-generation-events-v1/src/main/java/net/fabricmc/fabric/api/worldgen/event/v1/client/BiomeColorEvents.java
> + * Copyright (c) 2016, 2017, 2018, 2019 FabricMC
unless this is being copy + pasted from upstream this should say legacy fabric

2021-03-03 04:27 UTC, BluCobalt commented on fabric-world-generation-events-v1/src/main/java/net/fabricmc/fabric/impl/worldgen/event/OreCancellable.java
> + * Copyright (c) 2016, 2017, 2018, 2019 FabricMC
i cant do this for each one

2021-03-03 04:32 UTC, BluCobalt approved these changes
haha oops

2021-03-03 04:32 UTC, BoogieMonster1O1 commented
forgot a testmod, will make one soon

2021-03-26 16:01 UTC, BoogieMonster1O1 commented
this is broken anyway lel

2021-03-26 16:01 UTC, closed without merging

2021-03-26 16:02 UTC, Dolphin2Point1 commented
why tf are you doing this again this is dumb

2021-03-26 16:02 UTC, BoogieMonster1O1 commented
> why tf are you doing this again this is dumb

ikr its so dumb