Fluid api
Legacy-Fabric/fabric pull request #59
Opened 2020-12-25 04:00 UTC by BoogieMonster1O1

Taken from https://github.com/BoogieMonster1O1/nomcfluids

For information on how this works, read fluid-volume-api-debating in the fabricord

2020-12-25 05:05 UTC, CoolMineman requested changes
No test mod.
Not even an impl for Cauldrons.
Unclear how you even lookup FluidStorage from a world and pos.
There does not appear any way to revert a FluidTransaction which defeats the purpose of even having it.
FluidStorage has a questionable api where setStored directly mutates the underlying values and is the only way of inserting or extracting fluids.
The API provides multiple hard-coded checks (isValid and getMax[Input/Output]) the caller must check before mutating the underlying value instead of having an extract and insert and simply asking if the insertion or extraction can be done or not (through a simulation) or providing a rollback mechanism through a proper transaction system.
I fail to see the value in this API at all.

2020-12-25 05:12 UTC, hYdos commented
my review is basicly summed up by trollzers.

2020-12-25 05:26 UTC, BoogieMonster1O1 commented on fabric-fluid-volume-api-v1/src/main/java/net/legacyfabric/fabric/impl/fluid/volume/ImmutableFluidSettings.java
> +public class ImmutableFluidSettings implements FluidSettings {
no

2020-12-25 05:26 UTC, BoogieMonster1O1 commented on fabric-fluid-volume-api-v1/src/main/java/net/legacyfabric/fabric/api/fluid/volume/v1/util/Side.java
> +public enum Side {
yes

2020-12-25 05:26 UTC, BoogieMonster1O1 commented on fabric-fluid-volume-api-v1/src/test/java/net/legacyfabric/fabric/test/fluid/volume/FluidTransactionTest.java
> +		FluidType water = FluidType.getOrCreate(Blocks.WATER, FluidSettings.builder().luminance(0).color(Color.BLUE).build());
no

2020-12-25 05:26 UTC, BoogieMonster1O1 commented on fabric-fluid-volume-api-v1/src/main/java/net/legacyfabric/fabric/api/fluid/volume/v1/FluidType.java
> +public class FluidType {
no

2020-12-25 05:26 UTC, BoogieMonster1O1 commented on fabric-fluid-volume-api-v1/src/main/java/net/legacyfabric/fabric/api/fluid/volume/v1/FluidType.java
> +		return get(id).orElseGet(() -> new FluidType(id, block, Objects.requireNonNull(settings)));
yes

2020-12-25 05:26 UTC, BoogieMonster1O1 commented on fabric-fluid-volume-api-v1/src/main/java/net/legacyfabric/fabric/api/fluid/volume/v1/store/FluidTransaction.java
> +public class FluidTransaction {
transaction is a nice name

2020-12-25 05:27 UTC, BoogieMonster1O1 commented on fabric-fluid-volume-api-v1/src/main/java/net/legacyfabric/fabric/api/fluid/volume/v1/store/FluidStorageHandler.java
> +			this.storage.setStored(this.fluidType, this.side, stored.withSubtraction(extracted));
if only the first is valid but the other isnt its empty

2020-12-27 03:32 UTC, BoogieMonster1O1 commented
wasting my time on something that isn't needed

2020-12-27 03:32 UTC, closed without merging